version: "3"
services:
  wazi-on-sensors:
    image: waziup/wazi-on-sensors:beta
    build:
      context: ./
      # dockerfile: Dockerfile-dev
    container_name: waziup.wazi-on-sensors
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./:/go/src/wazi-on-sensors
      - ./:/root/app # The unix socket has to have this name and be in ./ : proxy.sock
    privileged: true #We need it to access i2c bus
    environment:
      - TEST_VAR=1
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes
    # restart_policy:
    #   condition: on-failure
    #   delay: 5s
    #   max_attempts: 3
    #   window: 120s
